
title:            'Random Yin'
url:              https://inrenping.github.io

author:
  name:           'Random Yin'
  first_name:     'Random' 
  last_name:      'Yin'

links: 
- title:          Twitter
  url:            //twitter.com/inrenping

- title:          Instagram
  url:            //instagram.com/inrenping

- title:          Douban
  url:            //www.douban.com/people/inrenping

- title:          Blog
  url:            //blog.inrenping.com
  
- title:          Mail
  url:            mailto:inrenping@gmail.com

articles: 
- title: 'BIO.'
  content: '<p>A Web Developer.</p><p>Commonly Id is <b>inrenping</b>, it is the Chinese name pinyin to rewrite.</p><p>I wanna to be the best programmer in my street,and till working hard for it.</p>'
  
- title: 'Anime'
  content: '<p>Anime lover.</p><p style="text-decoration: line-through;">Anime cured my empty soul.</p>'

- title: 'Ingress'
  content: '<p>Resistance.Lv14</p><p>Never do any Messions.</p>'