
title:            'Random Yin'
url:              https://inrenping.github.io

author:
  name:           'Random Yin'
  first_name:     'Random' 
  last_name:      'Yin'

links: 
- title:          Instagram
  url:            //instagram.com/inrenping
  class:          instagram-icon

- title:          Twitter
  url:            //twitter.com/inrenping
  class:          twitter-icon

- title:          Blog
  url:            //blog.inrenping.com
  class:          github-icon
  
- title:          Douban
  url:            //www.douban.com/people/inrenping
  class:          douban-icon

- title:          Mail
  url:            mailto:inrenping@gmail.com
  class:          gmail-icon

articles: 
- title: 'BIO.'
  content: '<p>A Web Developer.</p><p>Commonly Id is <b>inrenping</b>, although many people say it is difficult to read, in fact it is the Chinese name pinyin to rewrite.</p><p>Want to be the best programmer in my street,and till working hard for it.</p>'

- title: 'Ingress'
  content: '<p>Resistance.Lv12</p><p>Never do any Messions.</p>'
  
- title: 'Anime'
  content: '<p>Anime lover.</p><p style="text-decoration: line-through;">It cured my empty soul.</p>'
